import type { EngineResult, ExportConfig } from './exportEng/types';

function cssSlug(str: string): string {
  if (!str) return '';
  return String(str)
    .toLowerCase()
    .trim()
    .replace(/[\s_]+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function csvField(val: unknown): string {
  const s = String(val !== undefined && val !== null ? val : '');
  return s.includes(',') || s.includes('"') || s.includes('\n')
    ? `"${s.replace(/"/g, '""')}"`
    : s;
}

export const ExportFormatter = {
  toCSV(result: EngineResult, config: ExportConfig): string {
    const lines: string[] = [];

    lines.push('COLOR SCALES');
    const scaleEntries = Object.values(result.scales || {});
    const firstStep = scaleEntries.length ? Object.values(scaleEntries[0])[0] : null;
    const contrastKeys = firstStep ? Object.keys((firstStep as any).contrast || {}) : [];
    const scaleHeader = ['Group', 'Step', 'Hex', ...contrastKeys.flatMap((k) => [k + ' Contrast', k + ' Rating'])].join(',');
    lines.push(scaleHeader);
    for (const [colorName, scale] of Object.entries(result.scales || {})) {
      for (const [step, entry] of Object.entries(scale)) {
        const e = entry as any;
        const contrast = e.contrast as Record<string, { ratio: unknown; rating: unknown }> | undefined;
        const contrastCols = contrastKeys.flatMap((k) => [
          csvField(contrast && contrast[k] ? contrast[k].ratio : ''),
          csvField(contrast && contrast[k] ? contrast[k].rating : ''),
        ]);
        lines.push([csvField(colorName), csvField(step), csvField(entry.value), ...contrastCols].join(','));
      }
    }

    lines.push('');
    lines.push('ROLE TOKENS');
    lines.push('Color,Role,Variation,Theme,Hex,Contrast,Rating,Adjusted');
    for (const theme of Object.keys(result.tokens || {})) {
      const themeTokens = result.tokens[theme];
      if (!themeTokens) continue;
      for (const [colorName, roles] of Object.entries(themeTokens)) {
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleObj = (config.roles && config.roles[roleId]) || { name: roleId };
          const roleName = roleObj.name || roleId;
          const variationDefs =
            roleObj.customVariationList && roleObj.customVariations && roleObj.customVariations.length > 0
              ? roleObj.customVariations
              : config.variations ?? [];
          for (let i = 0; i < variationDefs.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const t = token as any;
            const contrast = t.contrast as { ratio: unknown; rating: unknown } | undefined;
            const dispName = variationDefs[i].shorthand || variationDefs[i].name;
            lines.push(
              [
                csvField(colorName),
                csvField(roleName),
                csvField(dispName),
                csvField(theme),
                csvField(token.value),
                csvField(contrast ? contrast.ratio : ''),
                csvField(contrast ? contrast.rating : ''),
                csvField(token.isAdjusted ? 'yes' : ''),
              ].join(','),
            );
          }
        }
      }
    }

    return lines.join('\n');
  },

  toCSS(result: EngineResult, config: ExportConfig): string {
    const date = new Date().toISOString();
    let css = `/* ${config.name ?? 'tokens'} — generated by Token Wand | ${date} */\n\n`;

    css += `:root {\n  /* ── Color Scales ── */\n`;
    for (const [colorName, scale] of Object.entries(result.scales)) {
      css += `\n  /* ${colorName} */\n`;
      for (const [step, entry] of Object.entries(scale)) {
        css += `  --${cssSlug(colorName)}-${cssSlug(String(step))}: ${entry.value};\n`;
      }
    }
    css += `}\n`;

    const themeKeys = Object.keys(result.tokens || {});
    for (let ti = 0; ti < themeKeys.length; ti++) {
      const theme = themeKeys[ti];
      const themeTokens = result.tokens[theme];
      if (!themeTokens) continue;
      const selector = ti === 0 ? `:root,\n[data-theme="${theme}"]` : `[data-theme="${theme}"]`;
      css += `\n/* ── ${theme.toUpperCase()} Semantic Tokens ── */\n${selector} {\n`;
      for (const [colorName, roles] of Object.entries(themeTokens)) {
        css += `\n  /* ${colorName} */\n`;
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleObj = (config.roles && config.roles[roleId]) || { name: roleId };
          const roleName = roleObj.name || roleId;
          const variationDefs =
            roleObj.customVariationList && roleObj.customVariations && roleObj.customVariations.length > 0
              ? roleObj.customVariations
              : config.variations ?? [];
          for (let i = 0; i < variationDefs.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const dispName = variationDefs[i].shorthand || variationDefs[i].name;
            css += `  --${cssSlug(colorName)}-${cssSlug(roleName)}-${cssSlug(dispName)}: ${token.value};\n`;
          }
        }
      }
      css += `}\n`;
    }

    const darkThemeKey = themeKeys.find((k) => k.toLowerCase() === 'dark');
    if (darkThemeKey) {
      const darkTokens = result.tokens[darkThemeKey];
      css += `\n/* ── OS Dark Mode Fallback ── */\n@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n`;
      for (const [colorName, roles] of Object.entries(darkTokens)) {
        for (const [roleId, variations] of Object.entries(roles)) {
          const roleObj = (config.roles && config.roles[roleId]) || { name: roleId };
          const roleName = roleObj.name || roleId;
          const variationDefs =
            roleObj.customVariationList && roleObj.customVariations && roleObj.customVariations.length > 0
              ? roleObj.customVariations
              : config.variations ?? [];
          for (let i = 0; i < variationDefs.length; i++) {
            const token = variations[String(i)];
            if (!token) continue;
            const dispName = variationDefs[i].shorthand || variationDefs[i].name;
            css += `    --${cssSlug(colorName)}-${cssSlug(roleName)}-${cssSlug(dispName)}: ${token.value};\n`;
          }
        }
      }
      css += `  }\n}\n`;
    }

    return css;
  },
};

export function generateScss(result: EngineResult, config: ExportConfig): string {
  if (!result || !result.scales) return '';
  const configVariations = config.variations ?? [];
  const systemName = config.name ?? 'tokens';
  const date = new Date().toISOString();

  const hr = (title: string) => `// ${'='.repeat(58)}\n// ${title}\n// ${'='.repeat(58)}\n\n`;

  let scss = `// ${systemName} — Auto-generated SCSS\n// Generated: ${date}\n// Do not edit manually.\n\n`;
  scss += `@use 'sass:map';\n\n`;

  scss += hr('COLOR SCALE VARIABLES');
  for (const [group, steps] of Object.entries(result.scales)) {
    scss += `// ${group}\n`;
    for (const [step, data] of Object.entries(steps)) {
      if (!data || !data.value) continue;
      scss += `$${cssSlug(group)}-${cssSlug(String(step))}: ${data.value};\n`;
    }
    scss += '\n';
  }

  scss += hr('PER-COLOR SCALE MAPS');
  for (const [group, steps] of Object.entries(result.scales)) {
    scss += `$scale-${cssSlug(group)}: (\n`;
    for (const [step, data] of Object.entries(steps)) {
      if (!data || !data.value) continue;
      scss += `  ${cssSlug(String(step))}: $${cssSlug(group)}-${cssSlug(String(step))},\n`;
    }
    scss += `);\n\n`;
  }

  const scssThemeKeys = Object.keys(result.tokens || {});
  for (const theme of scssThemeKeys) {
    const themeTokens = result.tokens[theme];
    if (!themeTokens) continue;
    scss += hr(`${theme.toUpperCase()} THEME TOKENS`);
    scss += `$tokens-${cssSlug(theme)}: (\n`;
    for (const [colorName, roles] of Object.entries(themeTokens)) {
      scss += `  // ${colorName}\n`;
      for (const [roleId, variations] of Object.entries(roles)) {
        const roleObj = (config.roles && config.roles[roleId]) || { name: roleId };
        const roleName = roleObj.name || roleId;
        const variationDefs =
          roleObj.customVariationList && roleObj.customVariations && roleObj.customVariations.length > 0
            ? roleObj.customVariations
            : configVariations;
        for (let i = 0; i < variationDefs.length; i++) {
          const token = variations[String(i)];
          if (!token) continue;
          const dispName = variationDefs[i].shorthand || variationDefs[i].name;
          const tokenKey = `${cssSlug(colorName)}-${cssSlug(roleName)}-${cssSlug(dispName)}`;
          let scaleRef: string;
          if (token.tokenRef) {
            const lastDash = token.tokenRef.lastIndexOf('-');
            scaleRef = `$${cssSlug(token.tokenRef.substring(0, lastDash))}-${cssSlug(token.tokenRef.substring(lastDash + 1))}`;
          } else {
            scaleRef = token.value;
          }
          const adjusted = token.isAdjusted ? ' /* ⚠ adjusted */' : '';
          scss += `  "${tokenKey}": ${scaleRef},${adjusted}\n`;
        }
      }
    }
    scss += `);\n\n`;
  }

  scss += hr('THEME MIXIN');
  scss += `/// Writes all token map entries as CSS custom properties.\n`;
  scss += `/// Usage: @include apply-theme($tokens-light);\n`;
  scss += `@mixin apply-theme($tokens) {\n`;
  scss += `  @each $name, $value in $tokens {\n`;
  scss += `    --#{$name}: #{$value};\n`;
  scss += `  }\n`;
  scss += `}\n\n`;

  scss += hr('THEME OUTPUT');
  scss += `// Class-based theming\n`;
  for (let ti = 0; ti < scssThemeKeys.length; ti++) {
    const theme = scssThemeKeys[ti];
    const varName = `$tokens-${cssSlug(theme)}`;
    if (ti === 0) {
      scss += `:root,\n[data-theme="${theme}"] {\n  @include apply-theme(${varName});\n}\n\n`;
    } else {
      scss += `[data-theme="${theme}"] {\n  @include apply-theme(${varName});\n}\n\n`;
    }
  }
  const scssDarkKey = scssThemeKeys.find((k) => k.toLowerCase() === 'dark');
  if (scssDarkKey) {
    scss += `// OS-level dark mode fallback\n`;
    scss += `@media (prefers-color-scheme: dark) {\n`;
    scss += `  :root:not([data-theme]) {\n`;
    scss += `    @include apply-theme($tokens-${cssSlug(scssDarkKey)});\n`;
    scss += `  }\n`;
    scss += `}\n`;
  }

  return scss;
}
