// Phase 6 acceptance — byte-diff fmt-lang's rendered output against REAL
// fmtReactNative.theme()/.index() output. The hardest of the 9 formats:
// a genuinely PER-SEGMENT-TYPE naming rule within one nested tree
// (variation stays kebab/_slug, color and role become camelCase/_camel —
// _setNested()'s own keyFn), a nested TS-object-literal tree (as const),
// and a two-file aggregator (index.ts importing every theme file) — the
// multi-file cross-reference case, not just a single self-contained file.
//
// Closes a real capability gap found here: renderNestedTree() previously
// took one NamingDef applied uniformly to every segment kind — React
// Native's own per-kind override couldn't be expressed. Fixed additively
// (an optional PerKindNaming map, see pipeline/nestedTree.ts) — every
// existing single-NamingDef caller (DTCG/Style Dictionary) is unaffected.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildDataset } from "../../src/data/adapter";
import { renderNestedTree } from "../../src/pipeline/nestedTree";
import { renderName, DEFAULT_NAMING } from "../../src/lang/defs/naming";
import { fmtReactNative } from "../../../src/shared/exportEng/fmtReactNative";
import { resolveExport, resolveScaleSteps } from "../../../src/shared/exportEng/resolve";
import type { EngineResult, ExportConfig } from "../../../src/shared/exportEng/types";

const fixture = JSON.parse(readFileSync(join(__dirname, "../fixtures/nmobile-fixture.json"), "utf-8")) as {
  result: EngineResult;
  exportConfig: ExportConfig;
};

// _renderTsLiteralLines()'s exact leaf shape: `"key": "value" as string,` —
// reproduced directly, since it's plain text composition, not a nesting
// decision (nestedTree.ts's job is the tree SHAPE, not this specific
// literal-line text convention).
function renderTsLiteralLines(node: Record<string, unknown>, indent: string): string[] {
  const lines: string[] = [];
  for (const key of Object.keys(node)) {
    const value = node[key];
    if (typeof value === "string") {
      lines.push(`${indent}${JSON.stringify(key)}: ${JSON.stringify(value)} as string,`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(...renderTsLiteralLines(value as Record<string, unknown>, `${indent}  `));
      lines.push(`${indent}},`);
    }
  }
  return lines;
}

test("fmt-lang reproduces fmtReactNative.theme()'s real per-theme TS-const output, byte-for-byte", () => {
  const { tokens: resolvedTokens } = resolveExport(fixture.result, fixture.exportConfig);
  const resolvedSteps = resolveScaleSteps(fixture.result, fixture.exportConfig);
  const themeName = "light";
  const real = fmtReactNative.theme(fixture.result, resolvedTokens, resolvedSteps, fixture.exportConfig, themeName);

  const ds = buildDataset(fixture.result, fixture.exportConfig);
  const camelNaming = { ...DEFAULT_NAMING, guardLeadingDigit: false, preferShorthand: true, case: "camel" as const };
  const kebabNaming = { ...DEFAULT_NAMING, guardLeadingDigit: false, preferShorthand: true, case: "kebab" as const };
  const themeTokens = ds.tokensForTheme(themeName);
  const projectName = fixture.exportConfig.name || "tokens";
  // _camel([themeName]): first part is never capitalized (see swift-file.test.ts's identical finding).
  const themeConst = themeName;

  const lines: string[] = [
    `// ${projectName} — ${themeName} theme tokens`,
    "// Auto-generated by Token Wand. Do not edit manually.\n",
    `export const ${themeConst}Tokens = {`,
  ];

  if (ds.scaleSteps.length > 0) {
    lines.push("  scale: {");
    let lastScaleColor: string | null = null;
    for (const step of ds.scaleSteps) {
      const colorKey = renderName([{ kind: "color", identity: step.data.color }], camelNaming);
      if (step.data.color.name !== lastScaleColor) {
        if (lastScaleColor !== null) lines.push("    },");
        lines.push(`    ${colorKey}: {`);
        lastScaleColor = step.data.color.name;
      }
      lines.push(`      ${JSON.stringify(step.data.stepKey)}: ${JSON.stringify(step.data.value)} as string,`);
    }
    if (lastScaleColor !== null) lines.push("    },");
    lines.push("  },");
  }

  if (ds.sourceColors.length > 0) {
    lines.push("  source: {");
    for (const colorRecord of ds.sourceColors) {
      const colorKey = renderName([{ kind: "color", identity: colorRecord.data.color }], camelNaming);
      lines.push(`    ${colorKey}: {`);
      lines.push(`      base: ${JSON.stringify(colorRecord.data.hex)} as string,`);
      const alphasForColor = ds.sourceAlphas.filter((a) => a.data.color.name === colorRecord.data.color.name);
      for (const alpha of alphasForColor) {
        const { r, g, b, a } = alpha.data.rgba;
        lines.push(`      alpha${alpha.data.opacity}: ${JSON.stringify(`rgba(${r}, ${g}, ${b}, ${a})`)} as string,`);
      }
      lines.push("    },");
    }
    lines.push("  },");
  }

  if (themeTokens.length > 0) {
    // The core per-kind naming rule: variation segments use kebabNaming
    // (matching _slug), color/role segments use camelNaming (matching
    // _camel) — expressed via renderNestedTree()'s new PerKindNaming param.
    const tree = renderNestedTree(
      themeTokens,
      fixture.exportConfig.tokenNameSegments as ("color" | "role" | "variation")[],
      camelNaming,
      (token) => token.data.value,
      { variation: kebabNaming }
    );
    lines.push("  tokens: {");
    lines.push(...renderTsLiteralLines(tree, "    "));
    lines.push("  },");
  }

  lines.push("} as const;\n");
  lines.push(`export type ${themeConst}TokensType = typeof ${themeConst}Tokens;`);
  const mine = lines.join("\n");

  assert.equal(mine, real);
});

test("fmt-lang reproduces fmtReactNative.index()'s real multi-file aggregator output, byte-for-byte", () => {
  const real = fmtReactNative.index(fixture.result, fixture.exportConfig);

  const ds = buildDataset(fixture.result, fixture.exportConfig);
  const projectName = fixture.exportConfig.name || "tokens";
  const kebabNaming = { ...DEFAULT_NAMING, guardLeadingDigit: false, case: "kebab" as const };
  const camelNaming = { ...DEFAULT_NAMING, guardLeadingDigit: false, case: "camel" as const };
  const themeIdent = (t: string) => renderName([{ kind: "step" as const, identity: { name: t, shorthand: null, segments: [t] } }], camelNaming);
  const themeSlug = (t: string) => renderName([{ kind: "step" as const, identity: { name: t, shorthand: null, segments: [t] } }], kebabNaming);

  const lines: string[] = [`// ${projectName} — token index`, "// Auto-generated by Token Wand. Do not edit manually.\n"];

  for (const theme of ds.themeNames) {
    lines.push(`import { ${themeIdent(theme)}Tokens } from './${themeSlug(theme)}';`);
  }
  lines.push("");
  lines.push(`export type Theme = ${ds.themeNames.map((t) => JSON.stringify(t)).join(" | ")};`);
  lines.push("");
  lines.push("const themeMap = {");
  for (const theme of ds.themeNames) {
    lines.push(`  ${JSON.stringify(theme)}: ${themeIdent(theme)}Tokens,`);
  }
  lines.push("} as const;\n");
  lines.push("export function useTokens(theme: Theme) {");
  lines.push(`  return themeMap[theme] ?? themeMap[${JSON.stringify(ds.themeNames[0] || "light")}];`);
  lines.push("}\n");
  for (const theme of ds.themeNames) {
    lines.push(`export { ${themeIdent(theme)}Tokens } from './${themeSlug(theme)}';`);
  }
  const mine = lines.join("\n");

  assert.equal(mine, real);
});
