// Phase 6 acceptance — byte-diff fmt-lang's rendered output against REAL
// fmtSwift.file() output. A distinct shape from every prior acceptance test:
// floating-point RGB channel-triple value formatting (0-1 range, 4 decimal
// places) rather than any hex/rgba-string kind, plus per-theme namespace
// (Swift extension/enum) wrapping instead of a flat file or nested tree.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { buildDataset } from "../../src/data/adapter";
import { parseHex } from "../../src/lang/stdlib/colorValue";
import { renderName, DEFAULT_NAMING } from "../../src/lang/defs/naming";
import { fmtSwift } from "../../../src/shared/exportEng/fmtSwift";
import { resolveExport, resolveScaleSteps } from "../../../src/shared/exportEng/resolve";
import type { EngineResult, ExportConfig } from "../../../src/shared/exportEng/types";

const fixture = JSON.parse(readFileSync(join(__dirname, "../fixtures/nmobile-fixture.json"), "utf-8")) as {
  result: EngineResult;
  exportConfig: ExportConfig;
};

function floatTriple(hex: string): { r: string; g: string; b: string } {
  const { r, g, b } = parseHex(hex);
  return { r: (r / 255).toFixed(4), g: (g / 255).toFixed(4), b: (b / 255).toFixed(4) };
}

test("fmt-lang reproduces fmtSwift.file()'s real per-theme UIColor/SwiftUI namespace output, byte-for-byte", () => {
  const { tokens: resolvedTokens } = resolveExport(fixture.result, fixture.exportConfig);
  const resolvedSteps = resolveScaleSteps(fixture.result, fixture.exportConfig);
  const themeName = "light";
  const real = fmtSwift.file(fixture.result, resolvedTokens, resolvedSteps, fixture.exportConfig, themeName);

  const ds = buildDataset(fixture.result, fixture.exportConfig);
  const namingDef = { ...DEFAULT_NAMING, guardLeadingDigit: false, preferShorthand: true, case: "camel" as const };
  const systemName = fixture.exportConfig.name || "Tokens";
  // _camel([themeName])'s real behavior: the FIRST part is never
  // capitalized (only parts after index 0 are) — so a single-element array
  // like ["light"] stays lowercase "light", despite fmtSwift.ts's own
  // comment claiming "light" -> "Light". Confirmed directly against
  // _camel()'s source (helpers.ts).
  const themeEnum = themeName;
  const themeTokens = ds.tokensForTheme(themeName);
  const hasScales = ds.scaleSteps.length > 0;

  const lines: string[] = [
    `// ${systemName} — ${themeName} theme`,
    "// Auto-generated by Token Wand. Do not edit manually.",
    `// Usage: UIColor.${themeEnum}.tokenName   |   Color.${themeEnum}.tokenName`,
    "import UIKit",
    "import SwiftUI",
    "",
    `extension UIColor { enum ${themeEnum} {} }`,
    `extension Color { enum ${themeEnum} {} }`,
    "",
  ];

  if (hasScales) {
    lines.push(`// MARK: - UIColor Scale (${themeName})`);
    lines.push(`extension UIColor.${themeEnum} {`);
    for (const step of ds.scaleSteps) {
      const varName = renderName(
        [
          { kind: "color", identity: step.data.color },
          { kind: "step", identity: { name: "scale", shorthand: null, segments: ["scale"] } },
          { kind: "step", identity: { name: step.data.stepKey, shorthand: null, segments: [step.data.stepKey] } },
        ],
        namingDef
      );
      const { r, g, b } = floatTriple(step.data.value);
      lines.push(`  static let ${varName} = UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: 1)`);
    }
    lines.push("}\n");
  }

  if (themeTokens.length > 0) {
    lines.push(`// MARK: - UIColor Semantic Tokens (${themeName})`);
    lines.push(`extension UIColor.${themeEnum} {`);
    for (const token of themeTokens) {
      const varName = renderName(
        token.data.segs.map((s) => ({ kind: s.type, identity: s.identity })),
        namingDef
      );
      const { r, g, b } = floatTriple(token.data.value);
      lines.push(`  static let ${varName} = UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: 1)`);
    }
    lines.push("}\n");
    lines.push(`// MARK: - SwiftUI Color Semantic Tokens (${themeName})`);
    lines.push(`extension Color.${themeEnum} {`);
    for (const token of themeTokens) {
      const varName = renderName(
        token.data.segs.map((s) => ({ kind: s.type, identity: s.identity })),
        namingDef
      );
      const { r, g, b } = floatTriple(token.data.value);
      lines.push(`  static let ${varName} = Color(red: ${r}, green: ${g}, blue: ${b})`);
    }
    lines.push("}");
  }

  if (ds.sourceColors.length > 0) {
    lines.push("");
    lines.push("// MARK: - Source Colors (raw, no theme processing)");
    lines.push(`extension UIColor.${themeEnum} {`);
    for (const colorRecord of ds.sourceColors) {
      const { r, g, b } = floatTriple(colorRecord.data.hex);
      const varName = renderName(
        [
          { kind: "color", identity: colorRecord.data.color },
          { kind: "step", identity: { name: "source", shorthand: null, segments: ["source"] } },
        ],
        namingDef
      );
      lines.push(`  static let ${varName} = UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: 1)`);
      const alphasForColor = ds.sourceAlphas.filter((a) => a.data.color.name === colorRecord.data.color.name);
      for (const alpha of alphasForColor) {
        const alphaVarName = renderName(
          [
            { kind: "color", identity: colorRecord.data.color },
            { kind: "step", identity: { name: "source", shorthand: null, segments: ["source"] } },
            { kind: "step", identity: { name: "alpha", shorthand: null, segments: ["alpha"] } },
            { kind: "step", identity: { name: String(alpha.data.opacity), shorthand: null, segments: [String(alpha.data.opacity)] } },
          ],
          { ...namingDef, guardLeadingDigit: false }
        );
        lines.push(`  static let ${alphaVarName} = UIColor(red: ${r}, green: ${g}, blue: ${b}, alpha: ${alpha.data.rgba.a.toFixed(4)})`);
      }
    }
    lines.push("}");
  }

  const mine = lines.join("\n");
  assert.equal(mine, real);
});
