import type { EngineResult, ExportConfig } from './types';
import { _colorLabel, _roleLabel, _varLabel, _stepLabel, _variationDefs, _slug, _camel } from './helpers';

export const fmtReactNative = {
  theme(result: EngineResult, config: ExportConfig, themeName: string): string {
    var themeTokens = result.tokens && result.tokens[themeName];
    var lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — " + themeName + " theme tokens");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    lines.push("export const " + _camel([themeName]) + "Tokens = {");
    var scaleNames = Object.keys(result.scales || {});
    if (scaleNames.length > 0) {
      lines.push("  scale: {");
      for (var ci = 0; ci < scaleNames.length; ci++) {
        var colorName = scaleNames[ci];
        var cLabel = _colorLabel(colorName, config);
        var scale = result.scales[colorName];
        lines.push("    " + _camel([cLabel]) + ": {");
        var steps = Object.keys(scale);
        for (var si = 0; si < steps.length; si++) {
          var step = steps[si];
          var entry = scale[step];
          lines.push("      " + JSON.stringify(_slug(_stepLabel(step, config))) + ": " + JSON.stringify(entry.value) + " as string,");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    if (themeTokens) {
      lines.push("  tokens: {");
      var colorNames = Object.keys(themeTokens);
      for (var ci2 = 0; ci2 < colorNames.length; ci2++) {
        var colorName2 = colorNames[ci2];
        var cLabel2 = _colorLabel(colorName2, config);
        lines.push("    " + _camel([cLabel2]) + ": {");
        var roles = themeTokens[colorName2];
        var roleIds = Object.keys(roles);
        for (var ri = 0; ri < roleIds.length; ri++) {
          var roleId = roleIds[ri];
          var roleObj = (config.roles && config.roles[roleId]) || { name: roleId };
          var rLabel = _roleLabel(roleObj, config);
          lines.push("      " + _camel([rLabel]) + ": {");
          var varDefs = _variationDefs(roleObj, config);
          var variations = roles[roleId];
          for (var vi = 0; vi < varDefs.length; vi++) {
            var token = variations[String(vi)];
            if (!token) continue;
            var vLabel = _varLabel(varDefs[vi], config);
            lines.push("        " + JSON.stringify(_slug(vLabel)) + ": " + JSON.stringify(token.value) + " as string,");
          }
          lines.push("      },");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    lines.push("} as const;\n");
    lines.push("export type " + _camel([themeName]) + "TokensType = typeof " + _camel([themeName]) + "Tokens;");
    return lines.join("\n");
  },

  index(result: EngineResult, config: ExportConfig): string {
    var themeKeys = Object.keys(result.tokens || {});
    var lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — token index");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    for (var ti = 0; ti < themeKeys.length; ti++) {
      var theme = themeKeys[ti];
      lines.push("import { " + _camel([theme]) + "Tokens } from './" + _slug(theme) + "';");
    }
    lines.push("");
    lines.push("export type Theme = " + themeKeys.map(function(t) { return JSON.stringify(t); }).join(" | ") + ";");
    lines.push("");
    lines.push("const themeMap = {");
    for (var ti2 = 0; ti2 < themeKeys.length; ti2++) {
      var theme2 = themeKeys[ti2];
      lines.push("  " + JSON.stringify(theme2) + ": " + _camel([theme2]) + "Tokens,");
    }
    lines.push("} as const;\n");
    lines.push("export function useTokens(theme: Theme) {");
    lines.push("  return themeMap[theme] ?? themeMap[" + JSON.stringify(themeKeys[0] || "light") + "];");
    lines.push("}\n");
    for (var ti3 = 0; ti3 < themeKeys.length; ti3++) {
      var theme3 = themeKeys[ti3];
      lines.push("export { " + _camel([theme3]) + "Tokens } from './" + _slug(theme3) + "';");
    }
    return lines.join("\n");
  },
};
