import type { EngineResult, ExportConfig } from './types';
import { _colorLabel, _stepLabel, _camel, _hexComponents, _eachToken } from './helpers';

export const fmtSwift = {
  file(result: EngineResult, config: ExportConfig, themeName: string): string {
    const themeTokens = result.tokens && result.tokens[themeName];
    const lines: string[] = [];
    const systemName = config.name || "Tokens";
    lines.push("// " + systemName + " — " + themeName + " theme");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.");
    lines.push("import UIKit");
    lines.push("import SwiftUI");
    lines.push("");
    const scaleNames = Object.keys(result.scales || {});
    lines.push("// MARK: - UIColor Scale (" + themeName + ")");
    lines.push("extension UIColor {");
    for (let ci = 0; ci < scaleNames.length; ci++) {
      const colorName = scaleNames[ci];
      const cLabel = _colorLabel(colorName, config);
      const scale = result.scales[colorName];
      const steps = Object.keys(scale);
      for (let si = 0; si < steps.length; si++) {
        const step = steps[si];
        const entry = scale[step];
        const varName = _camel([cLabel, "scale", _stepLabel(step, config)]);
        const rgb = _hexComponents(entry.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      }
    }
    lines.push("}\n");
    if (themeTokens) {
      lines.push("// MARK: - UIColor Semantic Tokens (" + themeName + ")");
      lines.push("extension UIColor {");
      _eachToken(result, config, function(theme, colorName, roleObj, varDef, token, cLabel, rLabel, vLabel, segs) {
        if (theme !== themeName) return;
        const varName = _camel(segs);
        const rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      });
      lines.push("}\n");
      lines.push("// MARK: - SwiftUI Color Semantic Tokens (" + themeName + ")");
      lines.push("extension Color {");
      _eachToken(result, config, function(theme, colorName, roleObj, varDef, token, cLabel, rLabel, vLabel, segs) {
        if (theme !== themeName) return;
        const varName = _camel(segs);
        const rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = Color(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ")");
      });
      lines.push("}");
    }
    return lines.join("\n");
  },
};
