/**
 * exportEng/fmtSwift.js
 * iOS / Swift — UIColor + SwiftUI Color static extensions, one file per theme.
 */

var fmtSwift = {

  file: function(result, config, themeName) {
    var themeTokens = result.tokens && result.tokens[themeName];
    var lines = [];
    var systemName = config.name || "Tokens";

    lines.push("// " + systemName + " — " + themeName + " theme");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.");
    lines.push("import UIKit");
    lines.push("import SwiftUI");
    lines.push("");

    // Helper used in both extensions
    var scaleNames = Object.keys(result.scales || {});

    // UIColor extension — scale
    lines.push("// MARK: - UIColor Scale (" + themeName + ")");
    lines.push("extension UIColor {");
    for (var ci = 0; ci < scaleNames.length; ci++) {
      var colorName = scaleNames[ci];
      var cLabel = _colorLabel(colorName, config);
      var scale = result.scales[colorName];
      var steps = Object.keys(scale);
      for (var si = 0; si < steps.length; si++) {
        var step = steps[si];
        var entry = scale[step];
        var varName = _camel([cLabel, "scale", _stepLabel(step, config)]);
        var rgb = _hexComponents(entry.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      }
    }
    lines.push("}\n");

    // UIColor extension — semantic tokens
    if (themeTokens) {
      lines.push("// MARK: - UIColor Semantic Tokens (" + themeName + ")");
      lines.push("extension UIColor {");
      _eachToken(result, config, function(theme, colorName, roleObj, varDef, token, cLabel, rLabel, vLabel, segs) {
        if (theme !== themeName) return;
        var varName = _camel(segs);
        var rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      });
      lines.push("}\n");

      // SwiftUI Color extension — semantic tokens
      lines.push("// MARK: - SwiftUI Color Semantic Tokens (" + themeName + ")");
      lines.push("extension Color {");
      _eachToken(result, config, function(theme, colorName, roleObj, varDef, token, cLabel, rLabel, vLabel, segs) {
        if (theme !== themeName) return;
        var varName = _camel(segs);
        var rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = Color(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ")");
      });
      lines.push("}");
    }

    return lines.join("\n");
  },
};
