import type { EngineResult, ExportConfig } from './types';
import { _slug, _camel, _setNested, _renderTsLiteralLines, _eachSourceColor } from './helpers';
import type { ResolvedToken, ResolvedScaleStep } from './resolve';

export const fmtReactNative = {
  theme(result: EngineResult, tokens: ResolvedToken[], scaleSteps: ResolvedScaleStep[], config: ExportConfig, themeName: string): string {
    const themeTokens = result.tokens && result.tokens[themeName];
    const lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — " + themeName + " theme tokens");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    lines.push("export const " + _camel([themeName]) + "Tokens = {");
    if (scaleSteps.length > 0) {
      lines.push("  scale: {");
      let lastScaleColor: string | null = null;
      for (const step of scaleSteps) {
        if (step.colorName !== lastScaleColor) {
          if (lastScaleColor !== null) lines.push("    },");
          lines.push("    " + _camel([step.cLabel]) + ": {");
          lastScaleColor = step.colorName;
        }
        lines.push("      " + JSON.stringify(_slug(step.stepKey)) + ": " + JSON.stringify(step.value) + " as string,");
      }
      if (lastScaleColor !== null) lines.push("    },");
      lines.push("  },");
    }
    const sourceColors = _eachSourceColor(config);
    if (sourceColors.length > 0) {
      lines.push("  source: {");
      for (const entry of sourceColors) {
        lines.push("    " + _camel([entry.cLabel]) + ": {");
        lines.push("      base: " + JSON.stringify(entry.hex) + " as string,");
        for (const alpha of entry.alphaVariants) {
          const { r, g, b, a } = alpha.rgba;
          lines.push("      alpha" + alpha.opacity + ": " + JSON.stringify(`rgba(${r}, ${g}, ${b}, ${a})`) + " as string,");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    if (themeTokens) {
      const tree: Record<string, unknown> = {};
      for (const token of tokens) {
        if (token.theme !== themeName) continue;
        _setNested(tree, token.segs, token.value, (s) => s.type === "variation" ? _slug(s.label) : _camel([s.label]));
      }
      lines.push("  tokens: {");
      lines.push(..._renderTsLiteralLines(tree, "    "));
      lines.push("  },");
    }
    lines.push("} as const;\n");
    lines.push("export type " + _camel([themeName]) + "TokensType = typeof " + _camel([themeName]) + "Tokens;");
    return lines.join("\n");
  },

  index(result: EngineResult, config: ExportConfig): string {
    const themeKeys = Object.keys(result.tokens || {});
    const lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — token index");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    for (let ti = 0; ti < themeKeys.length; ti++) {
      const theme = themeKeys[ti];
      lines.push("import { " + _camel([theme]) + "Tokens } from './" + _slug(theme) + "';");
    }
    lines.push("");
    lines.push("export type Theme = " + themeKeys.map(function(t) { return JSON.stringify(t); }).join(" | ") + ";");
    lines.push("");
    lines.push("const themeMap = {");
    for (let ti2 = 0; ti2 < themeKeys.length; ti2++) {
      const theme2 = themeKeys[ti2];
      lines.push("  " + JSON.stringify(theme2) + ": " + _camel([theme2]) + "Tokens,");
    }
    lines.push("} as const;\n");
    lines.push("export function useTokens(theme: Theme) {");
    lines.push("  return themeMap[theme] ?? themeMap[" + JSON.stringify(themeKeys[0] || "light") + "];");
    lines.push("}\n");
    for (let ti3 = 0; ti3 < themeKeys.length; ti3++) {
      const theme3 = themeKeys[ti3];
      lines.push("export { " + _camel([theme3]) + "Tokens } from './" + _slug(theme3) + "';");
    }
    return lines.join("\n");
  },
};
