import type { EngineResult, ExportConfig } from './types';
import { _colorLabel, _roleLabel, _varLabel, _stepLabel, _variationDefs, _slug, _camel, _eachSourceColor } from './helpers';

export const fmtReactNative = {
  theme(result: EngineResult, config: ExportConfig, themeName: string): string {
    const themeTokens = result.tokens && result.tokens[themeName];
    const lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — " + themeName + " theme tokens");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    lines.push("export const " + _camel([themeName]) + "Tokens = {");
    const scales = config.includeColorScalesCollection !== false ? (result.scales ?? {}) : {};
    const scaleNames = Object.keys(scales);
    if (scaleNames.length > 0) {
      lines.push("  scale: {");
      for (let ci = 0; ci < scaleNames.length; ci++) {
        const colorName = scaleNames[ci];
        const cLabel = _colorLabel(colorName, config);
        const scale = scales[colorName];
        lines.push("    " + _camel([cLabel]) + ": {");
        const steps = Object.keys(scale);
        for (let si = 0; si < steps.length; si++) {
          const step = steps[si];
          const entry = scale[step];
          lines.push("      " + JSON.stringify(_slug(_stepLabel(step, config))) + ": " + JSON.stringify(entry.value) + " as string,");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    const sourceColors = _eachSourceColor(config);
    if (sourceColors.length > 0) {
      lines.push("  source: {");
      for (const entry of sourceColors) {
        lines.push("    " + _camel([entry.cLabel]) + ": {");
        lines.push("      base: " + JSON.stringify(entry.hex) + " as string,");
        for (const alpha of entry.alphaVariants) {
          const { r, g, b, a } = alpha.rgba;
          lines.push("      alpha" + alpha.opacity + ": " + JSON.stringify(`rgba(${r}, ${g}, ${b}, ${a})`) + " as string,");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    if (themeTokens) {
      lines.push("  tokens: {");
      const colorNames = Object.keys(themeTokens);
      for (let ci2 = 0; ci2 < colorNames.length; ci2++) {
        const colorName2 = colorNames[ci2];
        const cLabel2 = _colorLabel(colorName2, config);
        lines.push("    " + _camel([cLabel2]) + ": {");
        const roles = themeTokens[colorName2] as Record<string, Record<string, import("./types").TokenEntry>>;
        const roleIds = Object.keys(roles);
        for (let ri = 0; ri < roleIds.length; ri++) {
          const roleId = roleIds[ri];
          const roleObj = (config.roles && config.roles[roleId]) || { name: roleId, shorthand: "" };
          const rLabel = _roleLabel(roleObj, config);
          lines.push("      " + _camel([rLabel]) + ": {");
          const varDefs = _variationDefs(roleObj, config);
          const variations = roles[roleId];
          for (let vi = 0; vi < varDefs.length; vi++) {
            const token = variations[String(vi)];
            if (!token) continue;
            const vLabel = _varLabel(varDefs[vi], config);
            lines.push("        " + JSON.stringify(_slug(vLabel)) + ": " + JSON.stringify(token.value) + " as string,");
          }
          lines.push("      },");
        }
        lines.push("    },");
      }
      lines.push("  },");
    }
    lines.push("} as const;\n");
    lines.push("export type " + _camel([themeName]) + "TokensType = typeof " + _camel([themeName]) + "Tokens;");
    return lines.join("\n");
  },

  index(result: EngineResult, config: ExportConfig): string {
    const themeKeys = Object.keys(result.tokens || {});
    const lines: string[] = [];
    lines.push("// " + (config.name || "tokens") + " — token index");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.\n");
    for (let ti = 0; ti < themeKeys.length; ti++) {
      const theme = themeKeys[ti];
      lines.push("import { " + _camel([theme]) + "Tokens } from './" + _slug(theme) + "';");
    }
    lines.push("");
    lines.push("export type Theme = " + themeKeys.map(function(t) { return JSON.stringify(t); }).join(" | ") + ";");
    lines.push("");
    lines.push("const themeMap = {");
    for (let ti2 = 0; ti2 < themeKeys.length; ti2++) {
      const theme2 = themeKeys[ti2];
      lines.push("  " + JSON.stringify(theme2) + ": " + _camel([theme2]) + "Tokens,");
    }
    lines.push("} as const;\n");
    lines.push("export function useTokens(theme: Theme) {");
    lines.push("  return themeMap[theme] ?? themeMap[" + JSON.stringify(themeKeys[0] || "light") + "];");
    lines.push("}\n");
    for (let ti3 = 0; ti3 < themeKeys.length; ti3++) {
      const theme3 = themeKeys[ti3];
      lines.push("export { " + _camel([theme3]) + "Tokens } from './" + _slug(theme3) + "';");
    }
    return lines.join("\n");
  },
};
