import type { EngineResult, ExportConfig } from './types';
import { _camel, _hexComponents, _eachSourceColor } from './helpers';
import type { ResolvedToken, ResolvedScaleStep } from './resolve';

// Each theme gets its own namespace enum so static members never collide when
// multiple theme files are added to the same Xcode target.
// Usage: UIColor.Light.brandPrimaryFillDefault, Color.Dark.brandNeutralTextSubtle
export const fmtSwift = {
  file(result: EngineResult, tokens: ResolvedToken[], scaleSteps: ResolvedScaleStep[], config: ExportConfig, themeName: string): string {
    const themeTokens = result.tokens && result.tokens[themeName];
    const lines: string[] = [];
    const systemName = config.name || "Tokens";
    const themeEnum = _camel([themeName]);  // "light" → "Light", "dark" → "Dark"
    lines.push("// " + systemName + " — " + themeName + " theme");
    lines.push("// Auto-generated by Token Wand. Do not edit manually.");
    lines.push("// Usage: UIColor." + themeEnum + ".tokenName   |   Color." + themeEnum + ".tokenName");
    lines.push("import UIKit");
    lines.push("import SwiftUI");
    lines.push("");
    const hasScales = scaleSteps.length > 0;

    // Declare the namespace enum once — re-declaring it in the same module is a Swift error.
    // Both UIColor.{Theme} and Color.{Theme} enums are declared here, then extended below.
    lines.push("extension UIColor { enum " + themeEnum + " {} }");
    lines.push("extension Color { enum " + themeEnum + " {} }");
    lines.push("");

    if (hasScales) {
      lines.push("// MARK: - UIColor Scale (" + themeName + ")");
      lines.push("extension UIColor." + themeEnum + " {");
      for (const step of scaleSteps) {
        const varName = _camel([step.cLabel, "scale", step.stepKey]);
        const rgb = _hexComponents(step.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      }
      lines.push("}\n");
    }
    if (themeTokens) {
      lines.push("// MARK: - UIColor Semantic Tokens (" + themeName + ")");
      lines.push("extension UIColor." + themeEnum + " {");
      for (const token of tokens) {
        if (token.theme !== themeName) continue;
        const varName = _camel(token.segs.map((s) => s.label));
        const rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
      }
      lines.push("}\n");
      lines.push("// MARK: - SwiftUI Color Semantic Tokens (" + themeName + ")");
      lines.push("extension Color." + themeEnum + " {");
      for (const token of tokens) {
        if (token.theme !== themeName) continue;
        const varName = _camel(token.segs.map((s) => s.label));
        const rgb = _hexComponents(token.value);
        lines.push("  static let " + varName + " = Color(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ")");
      }
      lines.push("}");
    }
    const sourceColors = _eachSourceColor(config);
    if (sourceColors.length > 0) {
      lines.push("\n// MARK: - Source Colors (raw, no theme processing)");
      lines.push("extension UIColor." + themeEnum + " {");
      for (const entry of sourceColors) {
        const rgb = _hexComponents(entry.hex);
        lines.push("  static let " + _camel([entry.cLabel, "source"]) + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: 1)");
        for (const alpha of entry.alphaVariants) {
          lines.push("  static let " + _camel([entry.cLabel, "source", "alpha", String(alpha.opacity)]) + " = UIColor(red: " + (rgb.r / 255).toFixed(4) + ", green: " + (rgb.g / 255).toFixed(4) + ", blue: " + (rgb.b / 255).toFixed(4) + ", alpha: " + alpha.rgba.a.toFixed(4) + ")");
        }
      }
      lines.push("}");
    }
    return lines.join("\n");
  },
};
